In [1]:
#adding to sys.path the directory for WRFChem Toolit code.
import sys
sys.path.insert(0,'/exports/csce/datastore/geos/users/s1878599/python_code')
import xarray as xr
from WRFChemToolkit.analysis import aerosols as ar

In [2]:
#open test data
data_path ='/exports/csce/datastore/geos/users/s1878599/python_code/sample_WRF_Chem_output'
ds = xr.open_dataset(data_path)

In [3]:
ar.calculate_pm25_species_3bins(ds)

In [4]:
ar.calculate_total_pm25(ds)

In [5]:
ds.pm25_calc[1,3,25,36].values

array(88.253426, dtype=float32)

In [6]:
ds.PM2_5_DRY[1,3,25,36].values

array(88.25342, dtype=float32)

In [7]:
ar.calculate_pm25_components(ds)

In [8]:
ds.pm25_POA

<xarray.DataArray 'pm25_POA' (Time: 12, bottom_top: 39, south_north: 119, west_east: 169)>
array([[[[0.30250224, 0.30907527, 0.32137236, ..., 0.7021956 ,
          1.4374197 , 2.9687097 ],
         [0.3054704 , 0.30906093, 0.32148325, ..., 1.6107645 ,
          1.8682117 , 1.8694253 ],
         [0.30835128, 0.31211013, 0.33011454, ..., 2.1792681 ,
          2.358184  , 2.3654423 ],
         ...,
         [0.30071282, 0.30104464, 0.3027372 , ..., 0.2568545 ,
          0.26184574, 0.26461866],
         [0.29916877, 0.29959828, 0.2993357 , ..., 0.2418278 ,
          0.25029573, 0.25409114],
         [0.29948702, 0.2995203 , 0.29488114, ..., 0.24262689,
          0.25197306, 0.25379315]],

        [[0.30125037, 0.3077772 , 0.32009804, ..., 0.5673682 ,
          0.84528095, 2.2612686 ],
         [0.3041815 , 0.30769342, 0.32007653, ..., 0.9263158 ,
          1.0632169 , 1.062861  ],
         [0.3070768 , 0.3107882 , 0.329193  , ..., 1.2992241 ,
          1.3963653 , 1.3993248 ],
         ..

In [13]:
ds['pm25_from_components'] = ds.pm25_SOA +ds.pm25_SIA  + ds.pm25_POA +ds.pm25_dust +ds.pm25_seasalt +ds.pm25_bc

In [18]:
ds.pm25_from_components[3,4,21,22].values

array(81.877106, dtype=float32)

In [19]:
ds.PM2_5_DRY[3,4,21,22].values

array(81.87711, dtype=float32)

In [20]:
ds.pm25_calc[3,4,21,22].values

array(81.877106, dtype=float32)

In [4]:
aerosols = ar.get_aerosols(ds)

TypeError: 'NoneType' object is not subscriptable

In [3]:
def get_data_subset(ds, var_list):
    
    """
    Utility function to substract from WRF-Chem output a subset of 
    selected variables.

    :param ds: WRF-chem output.
    :type ds: xarray DataSet.
    :param var_list: list of variables name to subset.
    :type ds: list of strings.
    
    :return: reduced dataset with selected variables only.
    :rtype: xarray DataSet.

    """
    
    #create empty dataset with same parent coords.
    subset = xr.Dataset(coords = dict(ds.coords))
    
    #fill subset with selected variables.
    
    for var in var_list:        
        subset[var] = ds[var]
        
    return subset

In [4]:
  aerosols = [
        'so4_a01','so4_a02', 'so4_a03', 'so4_a04', # sulfate.
        'no3_a01','no3_a02', 'no3_a03', 'no3_a04', # nitrate.
        'nh4_a01','nh4_a02', 'nh4_a03', 'nh4_a04', # ammonium.
        'bc_a01','bc_a02', 'bc_a03', 'bc_a04', # black carbon.
        'oc_a01','oc_a02', 'oc_a03', 'oc_a04', # organic carbon (POA).
        'smpa_a01','smpa_a02', 'smpa_a03', 'smpa_a04', # anthro SOA.
        'smpbb_a01','smpbb_a02', 'smpbb_a03', 'smpbb_a04', # biomass burning SOA.
        'biog1_o_a01','biog1_o_a02', 'biog1_o_a03', 'biog1_o_a04', # biogenic SOA (isporene).
        'biog1_c_a01','biog1_c_a02', 'biog1_c_a03', 'biog1_c_a04', # biogenic SOA (pinenes).       
        'glysoa_sfc_a01','glysoa_sfc_a02', 'glysoa_sfc_a03', 'glysoa_sfc_a04',  # glyoxal SOA.      
        'oin_a01','oin_a02', 'oin_a03', 'oin_a04', # dust.
        'na_a01','na_a02', 'na_a03', 'na_a04', # seasalt (sodium).
        'cl_a01','cl_a02', 'cl_a03', 'cl_a04', # seasalt (cloride).
        'PM2_5_DRY', # dry pm2.5 (prognostic variable).
        'water_a01','water_a02', 'water_a03', 'water_a04', # wet pm2.5 component.
        'num_a01','num_a02', 'num_a03', 'num_a04', # pm2.5 density number.
        'ALT' #inverse density.
        ]
    

In [5]:
aer = get_data_subset(ds, aerosols)

In [6]:
ar.calculate_pm25_species_3bins(aer)

In [7]:
ar.calculate_total_pm25(aer)

In [8]:
ar.calculate_pm25_components(aer)

In [10]:
aer.pm25_calc

<xarray.DataArray 'pm25_calc' (Time: 12, bottom_top: 39, south_north: 119, west_east: 169)>
array([[[[6.31627007e+01, 6.67410736e+01, 6.81876678e+01, ...,
          6.36829567e+00, 1.33072042e+01, 2.98549023e+01],
         [6.45981750e+01, 6.67428207e+01, 6.81920776e+01, ...,
          1.00989285e+01, 1.31413593e+01, 1.31463194e+01],
         [6.60308075e+01, 6.76898956e+01, 6.87516327e+01, ...,
          1.11121035e+01, 1.25897408e+01, 1.26115923e+01],
         ...,
         [6.20264397e+01, 6.20943336e+01, 6.14460678e+01, ...,
          2.25175476e+01, 2.28211575e+01, 2.30522537e+01],
         [6.38125114e+01, 6.38999672e+01, 6.40369034e+01, ...,
          2.26947117e+01, 2.31518955e+01, 2.34918480e+01],
         [6.38825874e+01, 6.38912544e+01, 6.75008774e+01, ...,
          2.27657833e+01, 2.33038960e+01, 2.34595985e+01]],

        [[6.29702682e+01, 6.64952927e+01, 6.79275818e+01, ...,
          5.82930470e+00, 7.41946077e+00, 2.25354309e+01],
         [6.43966370e+01, 6.64885788e+

In [11]:
ds_aer = ar.get_aerosols(ds)

In [12]:
ds_aer.PM2_5_DRY.values

array([[[[6.31627045e+01, 6.67410812e+01, 6.81876678e+01, ...,
          6.36829472e+00, 1.33072042e+01, 2.98549023e+01],
         [6.45981750e+01, 6.67428284e+01, 6.81920776e+01, ...,
          1.00989285e+01, 1.31413593e+01, 1.31463175e+01],
         [6.60308151e+01, 6.76898956e+01, 6.87516327e+01, ...,
          1.11121044e+01, 1.25897398e+01, 1.26115923e+01],
         ...,
         [6.20264397e+01, 6.20943336e+01, 6.14460678e+01, ...,
          2.25175514e+01, 2.28211575e+01, 2.30522518e+01],
         [6.38125114e+01, 6.38999634e+01, 6.40368958e+01, ...,
          2.26947117e+01, 2.31518955e+01, 2.34918480e+01],
         [6.38825874e+01, 6.38912506e+01, 6.75008774e+01, ...,
          2.27657833e+01, 2.33038940e+01, 2.34596004e+01]],

        [[6.29702606e+01, 6.64952927e+01, 6.79275818e+01, ...,
          5.82930470e+00, 7.41946077e+00, 2.25354309e+01],
         [6.43966370e+01, 6.64885788e+01, 6.79136200e+01, ...,
          7.44313240e+00, 8.66707039e+00, 8.65856075e+00],
        

In [13]:
ds_aer.pm25_calc.values

array([[[[6.31627007e+01, 6.67410736e+01, 6.81876678e+01, ...,
          6.36829567e+00, 1.33072042e+01, 2.98549023e+01],
         [6.45981750e+01, 6.67428207e+01, 6.81920776e+01, ...,
          1.00989285e+01, 1.31413593e+01, 1.31463194e+01],
         [6.60308075e+01, 6.76898956e+01, 6.87516327e+01, ...,
          1.11121035e+01, 1.25897408e+01, 1.26115923e+01],
         ...,
         [6.20264397e+01, 6.20943336e+01, 6.14460678e+01, ...,
          2.25175476e+01, 2.28211575e+01, 2.30522537e+01],
         [6.38125114e+01, 6.38999672e+01, 6.40369034e+01, ...,
          2.26947117e+01, 2.31518955e+01, 2.34918480e+01],
         [6.38825874e+01, 6.38912544e+01, 6.75008774e+01, ...,
          2.27657833e+01, 2.33038960e+01, 2.34595985e+01]],

        [[6.29702682e+01, 6.64952927e+01, 6.79275818e+01, ...,
          5.82930470e+00, 7.41946077e+00, 2.25354309e+01],
         [6.43966370e+01, 6.64885788e+01, 6.79136200e+01, ...,
          7.44313240e+00, 8.66706944e+00, 8.65856075e+00],
        

In [35]:
import numpy
numpy.testing.assert_almost_equal(ds_aer.pm25_calc.values, ds_aer.PM2_5_DRY.values, decimal=3
                             )

AssertionError: 
Arrays are not almost equal to 3 decimals

Mismatch: 0.000319%
Max absolute difference: 0.00292969
Max relative difference: 5.2783645e-07
 x: array([[[[6.316e+01, 6.674e+01, 6.819e+01, ..., 6.368e+00, 1.331e+01,
          2.985e+01],
         [6.460e+01, 6.674e+01, 6.819e+01, ..., 1.010e+01, 1.314e+01,...
 y: array([[[[6.316e+01, 6.674e+01, 6.819e+01, ..., 6.368e+00, 1.331e+01,
          2.985e+01],
         [6.460e+01, 6.674e+01, 6.819e+01, ..., 1.010e+01, 1.314e+01,...